// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mrequest.proto

package com.mdx.mobile.base;

public final class MRequest {
    private MRequest() {
    }
    
    public static void registerAllExtensions(com.google.protobuf.ExtensionRegistry registry) {
    }
    
    public interface Msg_RequestOrBuilder extends com.google.protobuf.MessageOrBuilder {
        
        // repeated .com.mdx.mobile.base.Msg_Post posts = 1;
        java.util.List<com.mdx.mobile.base.MRequest.Msg_Post> getPostsList();
        
        com.mdx.mobile.base.MRequest.Msg_Post getPosts(int index);
        
        int getPostsCount();
        
        java.util.List<? extends com.mdx.mobile.base.MRequest.Msg_PostOrBuilder> getPostsOrBuilderList();
        
        com.mdx.mobile.base.MRequest.Msg_PostOrBuilder getPostsOrBuilder(int index);
        
        // optional bytes requestMessage = 2;
        boolean hasRequestMessage();
        
        com.google.protobuf.ByteString getRequestMessage();
    }
    
    public static final class Msg_Request extends com.google.protobuf.GeneratedMessage implements Msg_RequestOrBuilder {
        // Use Msg_Request.newBuilder() to construct.
        private Msg_Request(Builder builder) {
            super(builder);
        }
        
        private Msg_Request(boolean noInit) {
        }
        
        private static final Msg_Request defaultInstance;
        
        public static Msg_Request getDefaultInstance() {
            return defaultInstance;
        }
        
        public Msg_Request getDefaultInstanceForType() {
            return defaultInstance;
        }
        
        public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
            return com.mdx.mobile.base.MRequest.internal_static_com_mdx_mobile_base_Msg_Request_descriptor;
        }
        
        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
            return com.mdx.mobile.base.MRequest.internal_static_com_mdx_mobile_base_Msg_Request_fieldAccessorTable;
        }
        
        private int bitField0_;
        
        // repeated .com.mdx.mobile.base.Msg_Post posts = 1;
        public static final int POSTS_FIELD_NUMBER = 1;
        
        private java.util.List<com.mdx.mobile.base.MRequest.Msg_Post> posts_;
        
        public java.util.List<com.mdx.mobile.base.MRequest.Msg_Post> getPostsList() {
            return posts_;
        }
        
        public java.util.List<? extends com.mdx.mobile.base.MRequest.Msg_PostOrBuilder> getPostsOrBuilderList() {
            return posts_;
        }
        
        public int getPostsCount() {
            return posts_.size();
        }
        
        public com.mdx.mobile.base.MRequest.Msg_Post getPosts(int index) {
            return posts_.get(index);
        }
        
        public com.mdx.mobile.base.MRequest.Msg_PostOrBuilder getPostsOrBuilder(int index) {
            return posts_.get(index);
        }
        
        // optional bytes requestMessage = 2;
        public static final int REQUESTMESSAGE_FIELD_NUMBER = 2;
        
        private com.google.protobuf.ByteString requestMessage_;
        
        public boolean hasRequestMessage() {
            return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        
        public com.google.protobuf.ByteString getRequestMessage() {
            return requestMessage_;
        }
        
        private void initFields() {
            posts_ = java.util.Collections.emptyList();
            requestMessage_ = com.google.protobuf.ByteString.EMPTY;
        }
        
        private byte memoizedIsInitialized = -1;
        
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized != -1)
                return isInitialized == 1;
            
            memoizedIsInitialized = 1;
            return true;
        }
        
        public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
            getSerializedSize();
            for (int i = 0; i < posts_.size(); i++) {
                output.writeMessage(1, posts_.get(i));
            }
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                output.writeBytes(2, requestMessage_);
            }
            getUnknownFields().writeTo(output);
        }
        
        private int memoizedSerializedSize = -1;
        
        public int getSerializedSize() {
            int size = memoizedSerializedSize;
            if (size != -1)
                return size;
            
            size = 0;
            for (int i = 0; i < posts_.size(); i++) {
                size += com.google.protobuf.CodedOutputStream.computeMessageSize(1, posts_.get(i));
            }
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                size += com.google.protobuf.CodedOutputStream.computeBytesSize(2, requestMessage_);
            }
            size += getUnknownFields().getSerializedSize();
            memoizedSerializedSize = size;
            return size;
        }
        
        private static final long serialVersionUID = 0L;
        
        @java.lang.Override
        protected java.lang.Object writeReplace() throws java.io.ObjectStreamException {
            return super.writeReplace();
        }
        
        public static com.mdx.mobile.base.MRequest.Msg_Request parseFrom(com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return newBuilder().mergeFrom(data).buildParsed();
        }
        
        public static com.mdx.mobile.base.MRequest.Msg_Request parseFrom(com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return newBuilder().mergeFrom(data, extensionRegistry).buildParsed();
        }
        
        public static com.mdx.mobile.base.MRequest.Msg_Request parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return newBuilder().mergeFrom(data).buildParsed();
        }
        
        public static com.mdx.mobile.base.MRequest.Msg_Request parseFrom(byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return newBuilder().mergeFrom(data, extensionRegistry).buildParsed();
        }
        
        public static com.mdx.mobile.base.MRequest.Msg_Request parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return newBuilder().mergeFrom(input).buildParsed();
        }
        
        public static com.mdx.mobile.base.MRequest.Msg_Request parseFrom(java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
            return newBuilder().mergeFrom(input, extensionRegistry).buildParsed();
        }
        
        public static com.mdx.mobile.base.MRequest.Msg_Request parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            Builder builder = newBuilder();
            if (builder.mergeDelimitedFrom(input)) {
                return builder.buildParsed();
            }
            else {
                return null;
            }
        }
        
        public static com.mdx.mobile.base.MRequest.Msg_Request parseDelimitedFrom(java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
            Builder builder = newBuilder();
            if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
                return builder.buildParsed();
            }
            else {
                return null;
            }
        }
        
        public static com.mdx.mobile.base.MRequest.Msg_Request parseFrom(com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return newBuilder().mergeFrom(input).buildParsed();
        }
        
        public static com.mdx.mobile.base.MRequest.Msg_Request parseFrom(com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
            return newBuilder().mergeFrom(input, extensionRegistry).buildParsed();
        }
        
        public static Builder newBuilder() {
            return Builder.create();
        }
        
        public Builder newBuilderForType() {
            return newBuilder();
        }
        
        public static Builder newBuilder(com.mdx.mobile.base.MRequest.Msg_Request prototype) {
            return newBuilder().mergeFrom(prototype);
        }
        
        public Builder toBuilder() {
            return newBuilder(this);
        }
        
        @java.lang.Override
        protected Builder newBuilderForType(com.google.protobuf.GeneratedMessage.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }
        
        public static final class Builder extends com.google.protobuf.GeneratedMessage.Builder<Builder> implements
                com.mdx.mobile.base.MRequest.Msg_RequestOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
                return com.mdx.mobile.base.MRequest.internal_static_com_mdx_mobile_base_Msg_Request_descriptor;
            }
            
            protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
                return com.mdx.mobile.base.MRequest.internal_static_com_mdx_mobile_base_Msg_Request_fieldAccessorTable;
            }
            
            // Construct using com.mdx.mobile.base.MRequest.Msg_Request.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }
            
            private Builder(BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }
            
            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
                    getPostsFieldBuilder();
                }
            }
            
            private static Builder create() {
                return new Builder();
            }
            
            public Builder clear() {
                super.clear();
                if (postsBuilder_ == null) {
                    posts_ = java.util.Collections.emptyList();
                    bitField0_ = (bitField0_ & ~0x00000001);
                }
                else {
                    postsBuilder_.clear();
                }
                requestMessage_ = com.google.protobuf.ByteString.EMPTY;
                bitField0_ = (bitField0_ & ~0x00000002);
                return this;
            }
            
            public Builder clone() {
                return create().mergeFrom(buildPartial());
            }
            
            public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
                return com.mdx.mobile.base.MRequest.Msg_Request.getDescriptor();
            }
            
            public com.mdx.mobile.base.MRequest.Msg_Request getDefaultInstanceForType() {
                return com.mdx.mobile.base.MRequest.Msg_Request.getDefaultInstance();
            }
            
            public com.mdx.mobile.base.MRequest.Msg_Request build() {
                com.mdx.mobile.base.MRequest.Msg_Request result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }
            
            private com.mdx.mobile.base.MRequest.Msg_Request buildParsed()
                    throws com.google.protobuf.InvalidProtocolBufferException {
                com.mdx.mobile.base.MRequest.Msg_Request result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result).asInvalidProtocolBufferException();
                }
                return result;
            }
            
            public com.mdx.mobile.base.MRequest.Msg_Request buildPartial() {
                com.mdx.mobile.base.MRequest.Msg_Request result = new com.mdx.mobile.base.MRequest.Msg_Request(this);
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                if (postsBuilder_ == null) {
                    if (((bitField0_ & 0x00000001) == 0x00000001)) {
                        posts_ = java.util.Collections.unmodifiableList(posts_);
                        bitField0_ = (bitField0_ & ~0x00000001);
                    }
                    result.posts_ = posts_;
                }
                else {
                    result.posts_ = postsBuilder_.build();
                }
                if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
                    to_bitField0_ |= 0x00000001;
                }
                result.requestMessage_ = requestMessage_;
                result.bitField0_ = to_bitField0_;
                onBuilt();
                return result;
            }
            
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof com.mdx.mobile.base.MRequest.Msg_Request) {
                    return mergeFrom((com.mdx.mobile.base.MRequest.Msg_Request) other);
                }
                else {
                    super.mergeFrom(other);
                    return this;
                }
            }
            
            public Builder mergeFrom(com.mdx.mobile.base.MRequest.Msg_Request other) {
                if (other == com.mdx.mobile.base.MRequest.Msg_Request.getDefaultInstance())
                    return this;
                if (postsBuilder_ == null) {
                    if (!other.posts_.isEmpty()) {
                        if (posts_.isEmpty()) {
                            posts_ = other.posts_;
                            bitField0_ = (bitField0_ & ~0x00000001);
                        }
                        else {
                            ensurePostsIsMutable();
                            posts_.addAll(other.posts_);
                        }
                        onChanged();
                    }
                }
                else {
                    if (!other.posts_.isEmpty()) {
                        if (postsBuilder_.isEmpty()) {
                            postsBuilder_.dispose();
                            postsBuilder_ = null;
                            posts_ = other.posts_;
                            bitField0_ = (bitField0_ & ~0x00000001);
                            postsBuilder_ = com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ? getPostsFieldBuilder()
                                    : null;
                        }
                        else {
                            postsBuilder_.addAllMessages(other.posts_);
                        }
                    }
                }
                if (other.hasRequestMessage()) {
                    setRequestMessage(other.getRequestMessage());
                }
                this.mergeUnknownFields(other.getUnknownFields());
                return this;
            }
            
            public final boolean isInitialized() {
                return true;
            }
            
            public Builder mergeFrom(com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
                com.google.protobuf.UnknownFieldSet.Builder unknownFields = com.google.protobuf.UnknownFieldSet.newBuilder(this.getUnknownFields());
                while (true) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            this.setUnknownFields(unknownFields.build());
                            onChanged();
                            return this;
                        default: {
                            if (!parseUnknownField(input, unknownFields, extensionRegistry, tag)) {
                                this.setUnknownFields(unknownFields.build());
                                onChanged();
                                return this;
                            }
                            break;
                        }
                        case 10: {
                            com.mdx.mobile.base.MRequest.Msg_Post.Builder subBuilder = com.mdx.mobile.base.MRequest.Msg_Post.newBuilder();
                            input.readMessage(subBuilder, extensionRegistry);
                            addPosts(subBuilder.buildPartial());
                            break;
                        }
                        case 18: {
                            bitField0_ |= 0x00000002;
                            requestMessage_ = input.readBytes();
                            break;
                        }
                    }
                }
            }
            
            private int bitField0_;
            
            // repeated .com.mdx.mobile.base.Msg_Post posts = 1;
            private java.util.List<com.mdx.mobile.base.MRequest.Msg_Post> posts_ = java.util.Collections.emptyList();
            
            private void ensurePostsIsMutable() {
                if (!((bitField0_ & 0x00000001) == 0x00000001)) {
                    posts_ = new java.util.ArrayList<com.mdx.mobile.base.MRequest.Msg_Post>(posts_);
                    bitField0_ |= 0x00000001;
                }
            }
            
            private com.google.protobuf.RepeatedFieldBuilder<com.mdx.mobile.base.MRequest.Msg_Post, com.mdx.mobile.base.MRequest.Msg_Post.Builder, com.mdx.mobile.base.MRequest.Msg_PostOrBuilder> postsBuilder_;
            
            public java.util.List<com.mdx.mobile.base.MRequest.Msg_Post> getPostsList() {
                if (postsBuilder_ == null) {
                    return java.util.Collections.unmodifiableList(posts_);
                }
                else {
                    return postsBuilder_.getMessageList();
                }
            }
            
            public int getPostsCount() {
                if (postsBuilder_ == null) {
                    return posts_.size();
                }
                else {
                    return postsBuilder_.getCount();
                }
            }
            
            public com.mdx.mobile.base.MRequest.Msg_Post getPosts(int index) {
                if (postsBuilder_ == null) {
                    return posts_.get(index);
                }
                else {
                    return postsBuilder_.getMessage(index);
                }
            }
            
            public Builder setPosts(int index, com.mdx.mobile.base.MRequest.Msg_Post value) {
                if (postsBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    ensurePostsIsMutable();
                    posts_.set(index, value);
                    onChanged();
                }
                else {
                    postsBuilder_.setMessage(index, value);
                }
                return this;
            }
            
            public Builder setPosts(int index, com.mdx.mobile.base.MRequest.Msg_Post.Builder builderForValue) {
                if (postsBuilder_ == null) {
                    ensurePostsIsMutable();
                    posts_.set(index, builderForValue.build());
                    onChanged();
                }
                else {
                    postsBuilder_.setMessage(index, builderForValue.build());
                }
                return this;
            }
            
            public Builder addPosts(com.mdx.mobile.base.MRequest.Msg_Post value) {
                if (postsBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    ensurePostsIsMutable();
                    posts_.add(value);
                    onChanged();
                }
                else {
                    postsBuilder_.addMessage(value);
                }
                return this;
            }
            
            public Builder addPosts(int index, com.mdx.mobile.base.MRequest.Msg_Post value) {
                if (postsBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    ensurePostsIsMutable();
                    posts_.add(index, value);
                    onChanged();
                }
                else {
                    postsBuilder_.addMessage(index, value);
                }
                return this;
            }
            
            public Builder addPosts(com.mdx.mobile.base.MRequest.Msg_Post.Builder builderForValue) {
                if (postsBuilder_ == null) {
                    ensurePostsIsMutable();
                    posts_.add(builderForValue.build());
                    onChanged();
                }
                else {
                    postsBuilder_.addMessage(builderForValue.build());
                }
                return this;
            }
            
            public Builder addPosts(int index, com.mdx.mobile.base.MRequest.Msg_Post.Builder builderForValue) {
                if (postsBuilder_ == null) {
                    ensurePostsIsMutable();
                    posts_.add(index, builderForValue.build());
                    onChanged();
                }
                else {
                    postsBuilder_.addMessage(index, builderForValue.build());
                }
                return this;
            }
            
            public Builder addAllPosts(java.lang.Iterable<? extends com.mdx.mobile.base.MRequest.Msg_Post> values) {
                if (postsBuilder_ == null) {
                    ensurePostsIsMutable();
                    super.addAll(values, posts_);
                    onChanged();
                }
                else {
                    postsBuilder_.addAllMessages(values);
                }
                return this;
            }
            
            public Builder clearPosts() {
                if (postsBuilder_ == null) {
                    posts_ = java.util.Collections.emptyList();
                    bitField0_ = (bitField0_ & ~0x00000001);
                    onChanged();
                }
                else {
                    postsBuilder_.clear();
                }
                return this;
            }
            
            public Builder removePosts(int index) {
                if (postsBuilder_ == null) {
                    ensurePostsIsMutable();
                    posts_.remove(index);
                    onChanged();
                }
                else {
                    postsBuilder_.remove(index);
                }
                return this;
            }
            
            public com.mdx.mobile.base.MRequest.Msg_Post.Builder getPostsBuilder(int index) {
                return getPostsFieldBuilder().getBuilder(index);
            }
            
            public com.mdx.mobile.base.MRequest.Msg_PostOrBuilder getPostsOrBuilder(int index) {
                if (postsBuilder_ == null) {
                    return posts_.get(index);
                }
                else {
                    return postsBuilder_.getMessageOrBuilder(index);
                }
            }
            
            public java.util.List<? extends com.mdx.mobile.base.MRequest.Msg_PostOrBuilder> getPostsOrBuilderList() {
                if (postsBuilder_ != null) {
                    return postsBuilder_.getMessageOrBuilderList();
                }
                else {
                    return java.util.Collections.unmodifiableList(posts_);
                }
            }
            
            public com.mdx.mobile.base.MRequest.Msg_Post.Builder addPostsBuilder() {
                return getPostsFieldBuilder().addBuilder(com.mdx.mobile.base.MRequest.Msg_Post.getDefaultInstance());
            }
            
            public com.mdx.mobile.base.MRequest.Msg_Post.Builder addPostsBuilder(int index) {
                return getPostsFieldBuilder().addBuilder(index,
                        com.mdx.mobile.base.MRequest.Msg_Post.getDefaultInstance());
            }
            
            public java.util.List<com.mdx.mobile.base.MRequest.Msg_Post.Builder> getPostsBuilderList() {
                return getPostsFieldBuilder().getBuilderList();
            }
            
            private com.google.protobuf.RepeatedFieldBuilder<com.mdx.mobile.base.MRequest.Msg_Post, com.mdx.mobile.base.MRequest.Msg_Post.Builder, com.mdx.mobile.base.MRequest.Msg_PostOrBuilder> getPostsFieldBuilder() {
                if (postsBuilder_ == null) {
                    postsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<com.mdx.mobile.base.MRequest.Msg_Post, com.mdx.mobile.base.MRequest.Msg_Post.Builder, com.mdx.mobile.base.MRequest.Msg_PostOrBuilder>(
                            posts_, ((bitField0_ & 0x00000001) == 0x00000001), getParentForChildren(), isClean());
                    posts_ = null;
                }
                return postsBuilder_;
            }
            
            // optional bytes requestMessage = 2;
            private com.google.protobuf.ByteString requestMessage_ = com.google.protobuf.ByteString.EMPTY;
            
            public boolean hasRequestMessage() {
                return ((bitField0_ & 0x00000002) == 0x00000002);
            }
            
            public com.google.protobuf.ByteString getRequestMessage() {
                return requestMessage_;
            }
            
            public Builder setRequestMessage(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000002;
                requestMessage_ = value;
                onChanged();
                return this;
            }
            
            public Builder clearRequestMessage() {
                bitField0_ = (bitField0_ & ~0x00000002);
                requestMessage_ = getDefaultInstance().getRequestMessage();
                onChanged();
                return this;
            }
            
            // @@protoc_insertion_point(builder_scope:com.mdx.mobile.base.Msg_Request)
        }
        
        static {
            defaultInstance = new Msg_Request(true);
            defaultInstance.initFields();
        }
        
        // @@protoc_insertion_point(class_scope:com.mdx.mobile.base.Msg_Request)
    }
    
    public interface Msg_PostOrBuilder extends com.google.protobuf.MessageOrBuilder {
        
        // optional string name = 1;
        boolean hasName();
        
        String getName();
        
        // optional string value = 2;
        boolean hasValue();
        
        String getValue();
    }
    
    public static final class Msg_Post extends com.google.protobuf.GeneratedMessage implements Msg_PostOrBuilder {
        // Use Msg_Post.newBuilder() to construct.
        private Msg_Post(Builder builder) {
            super(builder);
        }
        
        private Msg_Post(boolean noInit) {
        }
        
        private static final Msg_Post defaultInstance;
        
        public static Msg_Post getDefaultInstance() {
            return defaultInstance;
        }
        
        public Msg_Post getDefaultInstanceForType() {
            return defaultInstance;
        }
        
        public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
            return com.mdx.mobile.base.MRequest.internal_static_com_mdx_mobile_base_Msg_Post_descriptor;
        }
        
        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
            return com.mdx.mobile.base.MRequest.internal_static_com_mdx_mobile_base_Msg_Post_fieldAccessorTable;
        }
        
        private int bitField0_;
        
        // optional string name = 1;
        public static final int NAME_FIELD_NUMBER = 1;
        
        private java.lang.Object name_;
        
        public boolean hasName() {
            return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        
        public String getName() {
            java.lang.Object ref = name_;
            if (ref instanceof String) {
                return (String) ref;
            }
            else {
                com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                if (com.google.protobuf.Internal.isValidUtf8(bs)) {
                    name_ = s;
                }
                return s;
            }
        }
        
        private com.google.protobuf.ByteString getNameBytes() {
            java.lang.Object ref = name_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((String) ref);
                name_ = b;
                return b;
            }
            else {
                return (com.google.protobuf.ByteString) ref;
            }
        }
        
        // optional string value = 2;
        public static final int VALUE_FIELD_NUMBER = 2;
        
        private java.lang.Object value_;
        
        public boolean hasValue() {
            return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        
        public String getValue() {
            java.lang.Object ref = value_;
            if (ref instanceof String) {
                return (String) ref;
            }
            else {
                com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                if (com.google.protobuf.Internal.isValidUtf8(bs)) {
                    value_ = s;
                }
                return s;
            }
        }
        
        private com.google.protobuf.ByteString getValueBytes() {
            java.lang.Object ref = value_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((String) ref);
                value_ = b;
                return b;
            }
            else {
                return (com.google.protobuf.ByteString) ref;
            }
        }
        
        private void initFields() {
            name_ = "";
            value_ = "";
        }
        
        private byte memoizedIsInitialized = -1;
        
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized != -1)
                return isInitialized == 1;
            
            memoizedIsInitialized = 1;
            return true;
        }
        
        public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
            getSerializedSize();
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                output.writeBytes(1, getNameBytes());
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                output.writeBytes(2, getValueBytes());
            }
            getUnknownFields().writeTo(output);
        }
        
        private int memoizedSerializedSize = -1;
        
        public int getSerializedSize() {
            int size = memoizedSerializedSize;
            if (size != -1)
                return size;
            
            size = 0;
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                size += com.google.protobuf.CodedOutputStream.computeBytesSize(1, getNameBytes());
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                size += com.google.protobuf.CodedOutputStream.computeBytesSize(2, getValueBytes());
            }
            size += getUnknownFields().getSerializedSize();
            memoizedSerializedSize = size;
            return size;
        }
        
        private static final long serialVersionUID = 0L;
        
        @java.lang.Override
        protected java.lang.Object writeReplace() throws java.io.ObjectStreamException {
            return super.writeReplace();
        }
        
        public static com.mdx.mobile.base.MRequest.Msg_Post parseFrom(com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return newBuilder().mergeFrom(data).buildParsed();
        }
        
        public static com.mdx.mobile.base.MRequest.Msg_Post parseFrom(com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return newBuilder().mergeFrom(data, extensionRegistry).buildParsed();
        }
        
        public static com.mdx.mobile.base.MRequest.Msg_Post parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return newBuilder().mergeFrom(data).buildParsed();
        }
        
        public static com.mdx.mobile.base.MRequest.Msg_Post parseFrom(byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return newBuilder().mergeFrom(data, extensionRegistry).buildParsed();
        }
        
        public static com.mdx.mobile.base.MRequest.Msg_Post parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return newBuilder().mergeFrom(input).buildParsed();
        }
        
        public static com.mdx.mobile.base.MRequest.Msg_Post parseFrom(java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
            return newBuilder().mergeFrom(input, extensionRegistry).buildParsed();
        }
        
        public static com.mdx.mobile.base.MRequest.Msg_Post parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            Builder builder = newBuilder();
            if (builder.mergeDelimitedFrom(input)) {
                return builder.buildParsed();
            }
            else {
                return null;
            }
        }
        
        public static com.mdx.mobile.base.MRequest.Msg_Post parseDelimitedFrom(java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
            Builder builder = newBuilder();
            if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
                return builder.buildParsed();
            }
            else {
                return null;
            }
        }
        
        public static com.mdx.mobile.base.MRequest.Msg_Post parseFrom(com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return newBuilder().mergeFrom(input).buildParsed();
        }
        
        public static com.mdx.mobile.base.MRequest.Msg_Post parseFrom(com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
            return newBuilder().mergeFrom(input, extensionRegistry).buildParsed();
        }
        
        public static Builder newBuilder() {
            return Builder.create();
        }
        
        public Builder newBuilderForType() {
            return newBuilder();
        }
        
        public static Builder newBuilder(com.mdx.mobile.base.MRequest.Msg_Post prototype) {
            return newBuilder().mergeFrom(prototype);
        }
        
        public Builder toBuilder() {
            return newBuilder(this);
        }
        
        @java.lang.Override
        protected Builder newBuilderForType(com.google.protobuf.GeneratedMessage.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }
        
        public static final class Builder extends com.google.protobuf.GeneratedMessage.Builder<Builder> implements
                com.mdx.mobile.base.MRequest.Msg_PostOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
                return com.mdx.mobile.base.MRequest.internal_static_com_mdx_mobile_base_Msg_Post_descriptor;
            }
            
            protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
                return com.mdx.mobile.base.MRequest.internal_static_com_mdx_mobile_base_Msg_Post_fieldAccessorTable;
            }
            
            // Construct using com.mdx.mobile.base.MRequest.Msg_Post.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }
            
            private Builder(BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }
            
            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
                }
            }
            
            private static Builder create() {
                return new Builder();
            }
            
            public Builder clear() {
                super.clear();
                name_ = "";
                bitField0_ = (bitField0_ & ~0x00000001);
                value_ = "";
                bitField0_ = (bitField0_ & ~0x00000002);
                return this;
            }
            
            public Builder clone() {
                return create().mergeFrom(buildPartial());
            }
            
            public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
                return com.mdx.mobile.base.MRequest.Msg_Post.getDescriptor();
            }
            
            public com.mdx.mobile.base.MRequest.Msg_Post getDefaultInstanceForType() {
                return com.mdx.mobile.base.MRequest.Msg_Post.getDefaultInstance();
            }
            
            public com.mdx.mobile.base.MRequest.Msg_Post build() {
                com.mdx.mobile.base.MRequest.Msg_Post result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }
            
            private com.mdx.mobile.base.MRequest.Msg_Post buildParsed()
                    throws com.google.protobuf.InvalidProtocolBufferException {
                com.mdx.mobile.base.MRequest.Msg_Post result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result).asInvalidProtocolBufferException();
                }
                return result;
            }
            
            public com.mdx.mobile.base.MRequest.Msg_Post buildPartial() {
                com.mdx.mobile.base.MRequest.Msg_Post result = new com.mdx.mobile.base.MRequest.Msg_Post(this);
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
                    to_bitField0_ |= 0x00000001;
                }
                result.name_ = name_;
                if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
                    to_bitField0_ |= 0x00000002;
                }
                result.value_ = value_;
                result.bitField0_ = to_bitField0_;
                onBuilt();
                return result;
            }
            
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof com.mdx.mobile.base.MRequest.Msg_Post) {
                    return mergeFrom((com.mdx.mobile.base.MRequest.Msg_Post) other);
                }
                else {
                    super.mergeFrom(other);
                    return this;
                }
            }
            
            public Builder mergeFrom(com.mdx.mobile.base.MRequest.Msg_Post other) {
                if (other == com.mdx.mobile.base.MRequest.Msg_Post.getDefaultInstance())
                    return this;
                if (other.hasName()) {
                    setName(other.getName());
                }
                if (other.hasValue()) {
                    setValue(other.getValue());
                }
                this.mergeUnknownFields(other.getUnknownFields());
                return this;
            }
            
            public final boolean isInitialized() {
                return true;
            }
            
            public Builder mergeFrom(com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
                com.google.protobuf.UnknownFieldSet.Builder unknownFields = com.google.protobuf.UnknownFieldSet.newBuilder(this.getUnknownFields());
                while (true) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            this.setUnknownFields(unknownFields.build());
                            onChanged();
                            return this;
                        default: {
                            if (!parseUnknownField(input, unknownFields, extensionRegistry, tag)) {
                                this.setUnknownFields(unknownFields.build());
                                onChanged();
                                return this;
                            }
                            break;
                        }
                        case 10: {
                            bitField0_ |= 0x00000001;
                            name_ = input.readBytes();
                            break;
                        }
                        case 18: {
                            bitField0_ |= 0x00000002;
                            value_ = input.readBytes();
                            break;
                        }
                    }
                }
            }
            
            private int bitField0_;
            
            // optional string name = 1;
            private java.lang.Object name_ = "";
            
            public boolean hasName() {
                return ((bitField0_ & 0x00000001) == 0x00000001);
            }
            
            public String getName() {
                java.lang.Object ref = name_;
                if (!(ref instanceof String)) {
                    String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
                    name_ = s;
                    return s;
                }
                else {
                    return (String) ref;
                }
            }
            
            public Builder setName(String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000001;
                name_ = value;
                onChanged();
                return this;
            }
            
            public Builder clearName() {
                bitField0_ = (bitField0_ & ~0x00000001);
                name_ = getDefaultInstance().getName();
                onChanged();
                return this;
            }
            
            void setName(com.google.protobuf.ByteString value) {
                bitField0_ |= 0x00000001;
                name_ = value;
                onChanged();
            }
            
            // optional string value = 2;
            private java.lang.Object value_ = "";
            
            public boolean hasValue() {
                return ((bitField0_ & 0x00000002) == 0x00000002);
            }
            
            public String getValue() {
                java.lang.Object ref = value_;
                if (!(ref instanceof String)) {
                    String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
                    value_ = s;
                    return s;
                }
                else {
                    return (String) ref;
                }
            }
            
            public Builder setValue(String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000002;
                value_ = value;
                onChanged();
                return this;
            }
            
            public Builder clearValue() {
                bitField0_ = (bitField0_ & ~0x00000002);
                value_ = getDefaultInstance().getValue();
                onChanged();
                return this;
            }
            
            void setValue(com.google.protobuf.ByteString value) {
                bitField0_ |= 0x00000002;
                value_ = value;
                onChanged();
            }
            
            // @@protoc_insertion_point(builder_scope:com.mdx.mobile.base.Msg_Post)
        }
        
        static {
            defaultInstance = new Msg_Post(true);
            defaultInstance.initFields();
        }
        
        // @@protoc_insertion_point(class_scope:com.mdx.mobile.base.Msg_Post)
    }
    
    private static com.google.protobuf.Descriptors.Descriptor internal_static_com_mdx_mobile_base_Msg_Request_descriptor;
    
    private static com.google.protobuf.GeneratedMessage.FieldAccessorTable internal_static_com_mdx_mobile_base_Msg_Request_fieldAccessorTable;
    
    private static com.google.protobuf.Descriptors.Descriptor internal_static_com_mdx_mobile_base_Msg_Post_descriptor;
    
    private static com.google.protobuf.GeneratedMessage.FieldAccessorTable internal_static_com_mdx_mobile_base_Msg_Post_fieldAccessorTable;
    
    public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
        return descriptor;
    }
    
    private static com.google.protobuf.Descriptors.FileDescriptor descriptor;
    static {
        java.lang.String[] descriptorData = { "\n\016mrequest.proto\022\023com.mdx.mobile.base\"S\n"
                + "\013Msg_Request\022,\n\005posts\030\001 \003(\0132\035.com.mdx.mo"
                + "bile.base.Msg_Post\022\026\n\016requestMessage\030\002 \001"
                + "(\014\"\'\n\010Msg_Post\022\014\n\004name\030\001 \001(\t\022\r\n\005value\030\002 "
                + "\001(\tB\nB\010MRequest" };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner = new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
            public com.google.protobuf.ExtensionRegistry assignDescriptors(
                    com.google.protobuf.Descriptors.FileDescriptor root) {
                descriptor = root;
                internal_static_com_mdx_mobile_base_Msg_Request_descriptor = getDescriptor().getMessageTypes().get(0);
                internal_static_com_mdx_mobile_base_Msg_Request_fieldAccessorTable = new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                        internal_static_com_mdx_mobile_base_Msg_Request_descriptor, new java.lang.String[] { "Posts",
                                "RequestMessage", }, com.mdx.mobile.base.MRequest.Msg_Request.class,
                        com.mdx.mobile.base.MRequest.Msg_Request.Builder.class);
                internal_static_com_mdx_mobile_base_Msg_Post_descriptor = getDescriptor().getMessageTypes().get(1);
                internal_static_com_mdx_mobile_base_Msg_Post_fieldAccessorTable = new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                        internal_static_com_mdx_mobile_base_Msg_Post_descriptor, new java.lang.String[] { "Name",
                                "Value", }, com.mdx.mobile.base.MRequest.Msg_Post.class,
                        com.mdx.mobile.base.MRequest.Msg_Post.Builder.class);
                return null;
            }
        };
        com.google.protobuf.Descriptors.FileDescriptor.internalBuildGeneratedFileFrom(descriptorData,
                new com.google.protobuf.Descriptors.FileDescriptor[] {},
                assigner);
    }
    
    // @@protoc_insertion_point(outer_class_scope)
}
