// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: notify_data_android.proto

package com.mdx.mobile.base;

public final class Notify_Data {
  private Notify_Data() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface Msg_Notify_DataOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional string notifyTitle = 1;
    boolean hasNotifyTitle();
    String getNotifyTitle();
    
    // optional string notifyDescribe = 2;
    boolean hasNotifyDescribe();
    String getNotifyDescribe();
    
    // optional string notifyId = 3;
    boolean hasNotifyId();
    String getNotifyId();
    
    // optional string notifyUri = 4;
    boolean hasNotifyUri();
    String getNotifyUri();
    
    // optional int32 notifyType = 5;
    boolean hasNotifyType();
    int getNotifyType();
    
    // optional bytes notifyData = 6;
    boolean hasNotifyData();
    com.google.protobuf.ByteString getNotifyData();
  }
  public static final class Msg_Notify_Data extends
      com.google.protobuf.GeneratedMessage
      implements Msg_Notify_DataOrBuilder {
    // Use Msg_Notify_Data.newBuilder() to construct.
    private Msg_Notify_Data(Builder builder) {
      super(builder);
    }
    private Msg_Notify_Data(boolean noInit) {}
    
    private static final Msg_Notify_Data defaultInstance;
    public static Msg_Notify_Data getDefaultInstance() {
      return defaultInstance;
    }
    
    public Msg_Notify_Data getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.mdx.mobile.base.Notify_Data.internal_static_com_mdx_mobile_base_Msg_Notify_Data_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.mdx.mobile.base.Notify_Data.internal_static_com_mdx_mobile_base_Msg_Notify_Data_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional string notifyTitle = 1;
    public static final int NOTIFYTITLE_FIELD_NUMBER = 1;
    private java.lang.Object notifyTitle_;
    public boolean hasNotifyTitle() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getNotifyTitle() {
      java.lang.Object ref = notifyTitle_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          notifyTitle_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getNotifyTitleBytes() {
      java.lang.Object ref = notifyTitle_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        notifyTitle_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string notifyDescribe = 2;
    public static final int NOTIFYDESCRIBE_FIELD_NUMBER = 2;
    private java.lang.Object notifyDescribe_;
    public boolean hasNotifyDescribe() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getNotifyDescribe() {
      java.lang.Object ref = notifyDescribe_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          notifyDescribe_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getNotifyDescribeBytes() {
      java.lang.Object ref = notifyDescribe_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        notifyDescribe_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string notifyId = 3;
    public static final int NOTIFYID_FIELD_NUMBER = 3;
    private java.lang.Object notifyId_;
    public boolean hasNotifyId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public String getNotifyId() {
      java.lang.Object ref = notifyId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          notifyId_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getNotifyIdBytes() {
      java.lang.Object ref = notifyId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        notifyId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string notifyUri = 4;
    public static final int NOTIFYURI_FIELD_NUMBER = 4;
    private java.lang.Object notifyUri_;
    public boolean hasNotifyUri() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public String getNotifyUri() {
      java.lang.Object ref = notifyUri_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          notifyUri_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getNotifyUriBytes() {
      java.lang.Object ref = notifyUri_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        notifyUri_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional int32 notifyType = 5;
    public static final int NOTIFYTYPE_FIELD_NUMBER = 5;
    private int notifyType_;
    public boolean hasNotifyType() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public int getNotifyType() {
      return notifyType_;
    }
    
    // optional bytes notifyData = 6;
    public static final int NOTIFYDATA_FIELD_NUMBER = 6;
    private com.google.protobuf.ByteString notifyData_;
    public boolean hasNotifyData() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    public com.google.protobuf.ByteString getNotifyData() {
      return notifyData_;
    }
    
    private void initFields() {
      notifyTitle_ = "";
      notifyDescribe_ = "";
      notifyId_ = "";
      notifyUri_ = "";
      notifyType_ = 0;
      notifyData_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getNotifyTitleBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getNotifyDescribeBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getNotifyIdBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getNotifyUriBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(5, notifyType_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, notifyData_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getNotifyTitleBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getNotifyDescribeBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getNotifyIdBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getNotifyUriBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, notifyType_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, notifyData_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.mdx.mobile.base.Notify_Data.Msg_Notify_Data parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.mdx.mobile.base.Notify_Data.Msg_Notify_Data parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.mdx.mobile.base.Notify_Data.Msg_Notify_Data parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.mdx.mobile.base.Notify_Data.Msg_Notify_Data parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.mdx.mobile.base.Notify_Data.Msg_Notify_Data parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.mdx.mobile.base.Notify_Data.Msg_Notify_Data parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.mdx.mobile.base.Notify_Data.Msg_Notify_Data parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.mdx.mobile.base.Notify_Data.Msg_Notify_Data parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.mdx.mobile.base.Notify_Data.Msg_Notify_Data parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.mdx.mobile.base.Notify_Data.Msg_Notify_Data parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.mdx.mobile.base.Notify_Data.Msg_Notify_Data prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.mdx.mobile.base.Notify_Data.Msg_Notify_DataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.mdx.mobile.base.Notify_Data.internal_static_com_mdx_mobile_base_Msg_Notify_Data_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.mdx.mobile.base.Notify_Data.internal_static_com_mdx_mobile_base_Msg_Notify_Data_fieldAccessorTable;
      }
      
      // Construct using com.mdx.mobile.base.Notify_Data.Msg_Notify_Data.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        notifyTitle_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        notifyDescribe_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        notifyId_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        notifyUri_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        notifyType_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        notifyData_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.mdx.mobile.base.Notify_Data.Msg_Notify_Data.getDescriptor();
      }
      
      public com.mdx.mobile.base.Notify_Data.Msg_Notify_Data getDefaultInstanceForType() {
        return com.mdx.mobile.base.Notify_Data.Msg_Notify_Data.getDefaultInstance();
      }
      
      public com.mdx.mobile.base.Notify_Data.Msg_Notify_Data build() {
        com.mdx.mobile.base.Notify_Data.Msg_Notify_Data result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.mdx.mobile.base.Notify_Data.Msg_Notify_Data buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.mdx.mobile.base.Notify_Data.Msg_Notify_Data result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.mdx.mobile.base.Notify_Data.Msg_Notify_Data buildPartial() {
        com.mdx.mobile.base.Notify_Data.Msg_Notify_Data result = new com.mdx.mobile.base.Notify_Data.Msg_Notify_Data(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.notifyTitle_ = notifyTitle_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.notifyDescribe_ = notifyDescribe_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.notifyId_ = notifyId_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.notifyUri_ = notifyUri_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.notifyType_ = notifyType_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.notifyData_ = notifyData_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.mdx.mobile.base.Notify_Data.Msg_Notify_Data) {
          return mergeFrom((com.mdx.mobile.base.Notify_Data.Msg_Notify_Data)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.mdx.mobile.base.Notify_Data.Msg_Notify_Data other) {
        if (other == com.mdx.mobile.base.Notify_Data.Msg_Notify_Data.getDefaultInstance()) return this;
        if (other.hasNotifyTitle()) {
          setNotifyTitle(other.getNotifyTitle());
        }
        if (other.hasNotifyDescribe()) {
          setNotifyDescribe(other.getNotifyDescribe());
        }
        if (other.hasNotifyId()) {
          setNotifyId(other.getNotifyId());
        }
        if (other.hasNotifyUri()) {
          setNotifyUri(other.getNotifyUri());
        }
        if (other.hasNotifyType()) {
          setNotifyType(other.getNotifyType());
        }
        if (other.hasNotifyData()) {
          setNotifyData(other.getNotifyData());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              notifyTitle_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              notifyDescribe_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              notifyId_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              notifyUri_ = input.readBytes();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              notifyType_ = input.readInt32();
              break;
            }
            case 50: {
              bitField0_ |= 0x00000020;
              notifyData_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional string notifyTitle = 1;
      private java.lang.Object notifyTitle_ = "";
      public boolean hasNotifyTitle() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getNotifyTitle() {
        java.lang.Object ref = notifyTitle_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          notifyTitle_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setNotifyTitle(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        notifyTitle_ = value;
        onChanged();
        return this;
      }
      public Builder clearNotifyTitle() {
        bitField0_ = (bitField0_ & ~0x00000001);
        notifyTitle_ = getDefaultInstance().getNotifyTitle();
        onChanged();
        return this;
      }
      void setNotifyTitle(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        notifyTitle_ = value;
        onChanged();
      }
      
      // optional string notifyDescribe = 2;
      private java.lang.Object notifyDescribe_ = "";
      public boolean hasNotifyDescribe() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getNotifyDescribe() {
        java.lang.Object ref = notifyDescribe_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          notifyDescribe_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setNotifyDescribe(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        notifyDescribe_ = value;
        onChanged();
        return this;
      }
      public Builder clearNotifyDescribe() {
        bitField0_ = (bitField0_ & ~0x00000002);
        notifyDescribe_ = getDefaultInstance().getNotifyDescribe();
        onChanged();
        return this;
      }
      void setNotifyDescribe(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        notifyDescribe_ = value;
        onChanged();
      }
      
      // optional string notifyId = 3;
      private java.lang.Object notifyId_ = "";
      public boolean hasNotifyId() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public String getNotifyId() {
        java.lang.Object ref = notifyId_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          notifyId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setNotifyId(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        notifyId_ = value;
        onChanged();
        return this;
      }
      public Builder clearNotifyId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        notifyId_ = getDefaultInstance().getNotifyId();
        onChanged();
        return this;
      }
      void setNotifyId(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000004;
        notifyId_ = value;
        onChanged();
      }
      
      // optional string notifyUri = 4;
      private java.lang.Object notifyUri_ = "";
      public boolean hasNotifyUri() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public String getNotifyUri() {
        java.lang.Object ref = notifyUri_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          notifyUri_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setNotifyUri(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        notifyUri_ = value;
        onChanged();
        return this;
      }
      public Builder clearNotifyUri() {
        bitField0_ = (bitField0_ & ~0x00000008);
        notifyUri_ = getDefaultInstance().getNotifyUri();
        onChanged();
        return this;
      }
      void setNotifyUri(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000008;
        notifyUri_ = value;
        onChanged();
      }
      
      // optional int32 notifyType = 5;
      private int notifyType_ ;
      public boolean hasNotifyType() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public int getNotifyType() {
        return notifyType_;
      }
      public Builder setNotifyType(int value) {
        bitField0_ |= 0x00000010;
        notifyType_ = value;
        onChanged();
        return this;
      }
      public Builder clearNotifyType() {
        bitField0_ = (bitField0_ & ~0x00000010);
        notifyType_ = 0;
        onChanged();
        return this;
      }
      
      // optional bytes notifyData = 6;
      private com.google.protobuf.ByteString notifyData_ = com.google.protobuf.ByteString.EMPTY;
      public boolean hasNotifyData() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      public com.google.protobuf.ByteString getNotifyData() {
        return notifyData_;
      }
      public Builder setNotifyData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        notifyData_ = value;
        onChanged();
        return this;
      }
      public Builder clearNotifyData() {
        bitField0_ = (bitField0_ & ~0x00000020);
        notifyData_ = getDefaultInstance().getNotifyData();
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.mdx.mobile.base.Msg_Notify_Data)
    }
    
    static {
      defaultInstance = new Msg_Notify_Data(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.mdx.mobile.base.Msg_Notify_Data)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_mdx_mobile_base_Msg_Notify_Data_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_mdx_mobile_base_Msg_Notify_Data_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031notify_data_android.proto\022\023com.mdx.mob" +
      "ile.base\"\213\001\n\017Msg_Notify_Data\022\023\n\013notifyTi" +
      "tle\030\001 \001(\t\022\026\n\016notifyDescribe\030\002 \001(\t\022\020\n\010not" +
      "ifyId\030\003 \001(\t\022\021\n\tnotifyUri\030\004 \001(\t\022\022\n\nnotify" +
      "Type\030\005 \001(\005\022\022\n\nnotifyData\030\006 \001(\014B\rB\013Notify" +
      "_Data"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_mdx_mobile_base_Msg_Notify_Data_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_mdx_mobile_base_Msg_Notify_Data_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_mdx_mobile_base_Msg_Notify_Data_descriptor,
              new java.lang.String[] { "NotifyTitle", "NotifyDescribe", "NotifyId", "NotifyUri", "NotifyType", "NotifyData", },
              com.mdx.mobile.base.Notify_Data.Msg_Notify_Data.class,
              com.mdx.mobile.base.Notify_Data.Msg_Notify_Data.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
