// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mretn.proto

package com.mdx.mobile.base;

public final class Retn {
  private Retn() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface Msg_RetnOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional int32 errorCode = 1;
    boolean hasErrorCode();
    int getErrorCode();
    
    // optional string errorMsg = 2;
    boolean hasErrorMsg();
    String getErrorMsg();
    
    // optional string returnMethod = 3;
    boolean hasReturnMethod();
    String getReturnMethod();
    
    // optional bytes retnMessage = 4;
    boolean hasRetnMessage();
    com.google.protobuf.ByteString getRetnMessage();
  }
  public static final class Msg_Retn extends
      com.google.protobuf.GeneratedMessage
      implements Msg_RetnOrBuilder {
    // Use Msg_Retn.newBuilder() to construct.
    private Msg_Retn(Builder builder) {
      super(builder);
    }
    private Msg_Retn(boolean noInit) {}
    
    private static final Msg_Retn defaultInstance;
    public static Msg_Retn getDefaultInstance() {
      return defaultInstance;
    }
    
    public Msg_Retn getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.mdx.mobile.base.Retn.internal_static_com_mdx_mobile_base_Msg_Retn_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.mdx.mobile.base.Retn.internal_static_com_mdx_mobile_base_Msg_Retn_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional int32 errorCode = 1;
    public static final int ERRORCODE_FIELD_NUMBER = 1;
    private int errorCode_;
    public boolean hasErrorCode() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getErrorCode() {
      return errorCode_;
    }
    
    // optional string errorMsg = 2;
    public static final int ERRORMSG_FIELD_NUMBER = 2;
    private java.lang.Object errorMsg_;
    public boolean hasErrorMsg() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getErrorMsg() {
      java.lang.Object ref = errorMsg_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          errorMsg_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getErrorMsgBytes() {
      java.lang.Object ref = errorMsg_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        errorMsg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string returnMethod = 3;
    public static final int RETURNMETHOD_FIELD_NUMBER = 3;
    private java.lang.Object returnMethod_;
    public boolean hasReturnMethod() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public String getReturnMethod() {
      java.lang.Object ref = returnMethod_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          returnMethod_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getReturnMethodBytes() {
      java.lang.Object ref = returnMethod_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        returnMethod_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional bytes retnMessage = 4;
    public static final int RETNMESSAGE_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString retnMessage_;
    public boolean hasRetnMessage() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public com.google.protobuf.ByteString getRetnMessage() {
      return retnMessage_;
    }
    
    private void initFields() {
      errorCode_ = 0;
      errorMsg_ = "";
      returnMethod_ = "";
      retnMessage_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, errorCode_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getErrorMsgBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getReturnMethodBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, retnMessage_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, errorCode_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getErrorMsgBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getReturnMethodBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, retnMessage_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.mdx.mobile.base.Retn.Msg_Retn parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.mdx.mobile.base.Retn.Msg_Retn parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.mdx.mobile.base.Retn.Msg_Retn parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.mdx.mobile.base.Retn.Msg_Retn parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.mdx.mobile.base.Retn.Msg_Retn parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.mdx.mobile.base.Retn.Msg_Retn parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.mdx.mobile.base.Retn.Msg_Retn parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.mdx.mobile.base.Retn.Msg_Retn parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.mdx.mobile.base.Retn.Msg_Retn parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.mdx.mobile.base.Retn.Msg_Retn parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.mdx.mobile.base.Retn.Msg_Retn prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.mdx.mobile.base.Retn.Msg_RetnOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.mdx.mobile.base.Retn.internal_static_com_mdx_mobile_base_Msg_Retn_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.mdx.mobile.base.Retn.internal_static_com_mdx_mobile_base_Msg_Retn_fieldAccessorTable;
      }
      
      // Construct using com.mdx.mobile.base.Retn.Msg_Retn.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        errorCode_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        errorMsg_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        returnMethod_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        retnMessage_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.mdx.mobile.base.Retn.Msg_Retn.getDescriptor();
      }
      
      public com.mdx.mobile.base.Retn.Msg_Retn getDefaultInstanceForType() {
        return com.mdx.mobile.base.Retn.Msg_Retn.getDefaultInstance();
      }
      
      public com.mdx.mobile.base.Retn.Msg_Retn build() {
        com.mdx.mobile.base.Retn.Msg_Retn result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.mdx.mobile.base.Retn.Msg_Retn buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.mdx.mobile.base.Retn.Msg_Retn result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.mdx.mobile.base.Retn.Msg_Retn buildPartial() {
        com.mdx.mobile.base.Retn.Msg_Retn result = new com.mdx.mobile.base.Retn.Msg_Retn(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.errorCode_ = errorCode_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.errorMsg_ = errorMsg_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.returnMethod_ = returnMethod_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.retnMessage_ = retnMessage_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.mdx.mobile.base.Retn.Msg_Retn) {
          return mergeFrom((com.mdx.mobile.base.Retn.Msg_Retn)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.mdx.mobile.base.Retn.Msg_Retn other) {
        if (other == com.mdx.mobile.base.Retn.Msg_Retn.getDefaultInstance()) return this;
        if (other.hasErrorCode()) {
          setErrorCode(other.getErrorCode());
        }
        if (other.hasErrorMsg()) {
          setErrorMsg(other.getErrorMsg());
        }
        if (other.hasReturnMethod()) {
          setReturnMethod(other.getReturnMethod());
        }
        if (other.hasRetnMessage()) {
          setRetnMessage(other.getRetnMessage());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              errorCode_ = input.readInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              errorMsg_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              returnMethod_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              retnMessage_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional int32 errorCode = 1;
      private int errorCode_ ;
      public boolean hasErrorCode() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getErrorCode() {
        return errorCode_;
      }
      public Builder setErrorCode(int value) {
        bitField0_ |= 0x00000001;
        errorCode_ = value;
        onChanged();
        return this;
      }
      public Builder clearErrorCode() {
        bitField0_ = (bitField0_ & ~0x00000001);
        errorCode_ = 0;
        onChanged();
        return this;
      }
      
      // optional string errorMsg = 2;
      private java.lang.Object errorMsg_ = "";
      public boolean hasErrorMsg() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getErrorMsg() {
        java.lang.Object ref = errorMsg_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          errorMsg_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setErrorMsg(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        errorMsg_ = value;
        onChanged();
        return this;
      }
      public Builder clearErrorMsg() {
        bitField0_ = (bitField0_ & ~0x00000002);
        errorMsg_ = getDefaultInstance().getErrorMsg();
        onChanged();
        return this;
      }
      void setErrorMsg(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        errorMsg_ = value;
        onChanged();
      }
      
      // optional string returnMethod = 3;
      private java.lang.Object returnMethod_ = "";
      public boolean hasReturnMethod() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public String getReturnMethod() {
        java.lang.Object ref = returnMethod_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          returnMethod_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setReturnMethod(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        returnMethod_ = value;
        onChanged();
        return this;
      }
      public Builder clearReturnMethod() {
        bitField0_ = (bitField0_ & ~0x00000004);
        returnMethod_ = getDefaultInstance().getReturnMethod();
        onChanged();
        return this;
      }
      void setReturnMethod(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000004;
        returnMethod_ = value;
        onChanged();
      }
      
      // optional bytes retnMessage = 4;
      private com.google.protobuf.ByteString retnMessage_ = com.google.protobuf.ByteString.EMPTY;
      public boolean hasRetnMessage() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public com.google.protobuf.ByteString getRetnMessage() {
        return retnMessage_;
      }
      public Builder setRetnMessage(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        retnMessage_ = value;
        onChanged();
        return this;
      }
      public Builder clearRetnMessage() {
        bitField0_ = (bitField0_ & ~0x00000008);
        retnMessage_ = getDefaultInstance().getRetnMessage();
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.mdx.mobile.base.Msg_Retn)
    }
    
    static {
      defaultInstance = new Msg_Retn(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.mdx.mobile.base.Msg_Retn)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_mdx_mobile_base_Msg_Retn_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_mdx_mobile_base_Msg_Retn_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013mretn.proto\022\023com.mdx.mobile.base\"Z\n\010Ms" +
      "g_Retn\022\021\n\terrorCode\030\001 \001(\005\022\020\n\010errorMsg\030\002 " +
      "\001(\t\022\024\n\014returnMethod\030\003 \001(\t\022\023\n\013retnMessage" +
      "\030\004 \001(\014B\006B\004Retn"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_mdx_mobile_base_Msg_Retn_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_mdx_mobile_base_Msg_Retn_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_mdx_mobile_base_Msg_Retn_descriptor,
              new java.lang.String[] { "ErrorCode", "ErrorMsg", "ReturnMethod", "RetnMessage", },
              com.mdx.mobile.base.Retn.Msg_Retn.class,
              com.mdx.mobile.base.Retn.Msg_Retn.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
